// favorites
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES"
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES"

// home
export const UPADTAE_MAIN_LOCATION_TO_VIEW = "UPDATE_MAIN_LOCATION_TO_VIEW"
export const FETCH_CURRENT_WEATHER_REQUEST = "FETCH_CURRENT_WEATHER_REQUEST"
export const FETCH_CURRENT_WEATHER_SUCCESS = "FETCH_CURRENT_WEATHER_SUCCESS"
export const FETCH_CURRENT_WEATHER_FAILURE = "FETCH_CURRENT_WEATHER_FAILURE"