// favorites
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES"
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES"

// home
export const UPADTAE_MAIN_LOCATION_TO_VIEW = "UPDATE_MAIN_LOCATION_TO_VIEW"

// current weather
export const FETCH_CURRENT_WEATHER_REQUEST = "FETCH_CURRENT_WEATHER_REQUEST"
export const FETCH_CURRENT_WEATHER_SUCCESS = "FETCH_CURRENT_WEATHER_SUCCESS"
export const FETCH_CURRENT_WEATHER_FAILURE = "FETCH_CURRENT_WEATHER_FAILURE"

// 5 day forcast
export const FETCH_FORCAST_REQUEST = "FETCH_FORCAST_REQUEST"
export const FETCH_FORCAST_SUCCESS = "FETCH_FORCAST_SUCCESS"
export const FETCH_FORCAST_FAILURE = "FETCH_FORCAST_FAILURE"

// locations
export const FETCH_LOCATIONS_REQUEST = "FETCH_LOCATIONS_REQUEST"
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS"
export const FETCH_LOCATIONS_FAILURE = "FETCH_LOCATIONS_FAILURE"

// errors
export const ADD_TO_ERROR_STACK = "ADD_TO_ERROR_STACK"
export const REMOVE_FROM_ERROR_STACK = "REMOVE_FROM_ERROR_STACK"

// app
export const CHANGE_APP_THEME = "CHANGE_APP_THEME"