// favorites
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES"
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES"

// home
export const UPADTAE_MAIN_LOCATION_TO_VIEW = "UPDATE_MAIN_LOCATION_TO_VIEW"